-- MySQL Script generated by MySQL Workbench
-- mar 21 nov 2017 19:04:59 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema escomTitulos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escomTitulos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escomTitulos` DEFAULT CHARACTER SET utf8 ;
USE `escomTitulos` ;

-- -----------------------------------------------------
-- Table `escomTitulos`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escomTitulos`.`carrera` (
  `idcarrera` INT NOT NULL AUTO_INCREMENT,
  `carrera_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idcarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escomTitulos`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escomTitulos`.`especialidad` (
  `idespecialidad` INT NOT NULL AUTO_INCREMENT,
  `especialidad_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idespecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escomTitulos`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escomTitulos`.`periodo` (
  `idperiodo` INT NOT NULL AUTO_INCREMENT,
  `periodo_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idperiodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escomTitulos`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escomTitulos`.`plan` (
  `idplan` INT NOT NULL AUTO_INCREMENT,
  `plan_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idplan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escomTitulos`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escomTitulos`.`estudiante` (
  `idestudiante` INT NOT NULL AUTO_INCREMENT,
  `estudiante_carrera` INT NULL,
  `estudiante_especialidad` INT NULL,
  `estudiante_periodo` INT NULL,
  `estudiante_plan` INT NULL,
  `estudiante_curp` VARCHAR(45) NULL,
  `estudiante_turno` VARCHAR(45) NULL,
  `estudiante_genero` TINYINT(1) NULL,
  `estudiante_edad` INT NULL,
  `estudiante_fecha_nacimiento` DATETIME NULL,
  `estudiante_telefono` VARCHAR(45) NULL,
  `estudiante_movil` VARCHAR(45) NULL,
  `estudiante_email` VARCHAR(45) NULL,
  PRIMARY KEY (`idestudiante`),
  INDEX `fk_estudiante_carrera_idx` (`estudiante_carrera` ASC),
  INDEX `fk_estudiante_especialidad_idx` (`estudiante_especialidad` ASC),
  INDEX `fk_estudiante_periodo_idx` (`estudiante_periodo` ASC),
  INDEX `fk_estudiante_plan_idx` (`estudiante_plan` ASC),
  CONSTRAINT `fk_estudiante_carrera`
    FOREIGN KEY (`estudiante_carrera`)
    REFERENCES `escomTitulos`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_especialidad`
    FOREIGN KEY (`estudiante_especialidad`)
    REFERENCES `escomTitulos`.`especialidad` (`idespecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_periodo`
    FOREIGN KEY (`estudiante_periodo`)
    REFERENCES `escomTitulos`.`periodo` (`idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_plan`
    FOREIGN KEY (`estudiante_plan`)
    REFERENCES `escomTitulos`.`plan` (`idplan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escomTitulos`.`estudiante_historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escomTitulos`.`estudiante_historial` (
  `idestudiante` INT NOT NULL AUTO_INCREMENT,
  `estudiante_total_creditos` DOUBLE NULL,
  `estudiante_materias_reprobadas` INT NULL,
  `estudiante_materias_acreditadas` INT NULL,
  `estudiante_creditos_inscritos` DOUBLE NULL,
  `estudiante_materias_inscritas` INT NULL,
  `estudiante_promedio` DOUBLE NULL,
  PRIMARY KEY (`idestudiante`),
  CONSTRAINT `fk_estudiante_historial`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `escomTitulos`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
